###
POST https://ag-chatapp.herokuapp.com/login
Content-Type: application/json

{
    "username" : "gaurav",
    "password" : "Arman@13"
}

###
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "name" : "Gaurav Yadav",
    "username" : "gaurav",
    "email" : "gauravyadav2609@gmail.com",
    "password" : "Arman@13"
}

###
POST https://ag-chatapp.herokuapp.com/resend
Content-Type: application/json

{ 
    "username": "gaurav"
}
