###
POST https://ag-chatapp.herokuapp.com/login
Content-Type: application/json

{
    "email" : "gauravyadav2609@gmail.com",
    "password" : "Arman@13"
}

###
POST https://ag-chatapp.herokuapp.com/register
Content-Type: application/json

{
    "name" : "Gaurav Yadav",
    "email" : "gauravyadav2609@gmail.com",
    "password" : "Arman@13",
    "image" : "abchh"
}

###
POST https://ag-chatapp.herokuapp.com/resend
Content-Type: application/json

{ 
    "email": "gauravyadav2609@gmail.com"
}
